Signinscreen
aura-cz2006/aura-app pull request #11
Opened 2022-03-18 17:09 UTC by jamiegoh

Hello besties, this is just the sign in screen with just the button that redirects to map <3

2022-03-20 00:44 UTC, RealDyllon commented
@jamiegoh navigation needs to be replaced with the new go_router dependency.

2022-03-20 10:57 UTC, RealDyllon commented
@jamiegoh any update on this?

2022-03-20 14:29 UTC, jamiegoh commented
@RealDyllon i added the go router thingy

2022-03-21 11:07 UTC, RealDyllon requested changes

2022-03-21 11:07 UTC, RealDyllon commented on pubspec.yaml
>    #   - images/a_dot_ham.jpeg
remove this

2022-03-21 11:07 UTC, RealDyllon commented on README.md
> +#test
remove this

2022-03-21 11:07 UTC, RealDyllon commented on lib/view/signin/signin_screen.dart
> +import 'package:flutter/material.dart';
good

2022-03-21 11:07 UTC, RealDyllon commented on lib/router.dart
> +              const SigninScreen())
good stuff

2022-03-21 11:07 UTC, RealDyllon commented on pubspec.yaml
> +    - assets/singpass.png
genius 5/5 👍🏼

2022-03-21 11:10 UTC, jamiegoh commented
@RealDyllon fixed bestie

2022-03-21 11:12 UTC, RealDyllon approved these changes
LGTM great stuff jamie keep it up

2022-03-21 11:12 UTC, merged